name: Commit cheat

on:
  workflow_dispatch:
      
  schedule:
  - cron: "0 */11 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify Changelog.md
        run: |
          cat > Changelog.md
          curl -H "Accept: text/plain" https://icanhazdadjoke.com > Changelog.md
          sed -i 's/^/## /gi' Changelog.md
          
      - name: Commit changes
        run: |
          echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > .git-credentials
          git config --local user.email ${{ secrets.GH_MAIL }}
          git config --local user.name ${{ secrets.GH_NAME }}
          git config --global --add safe.directory /github/workspace
          git add Changelog.md
          git commit -s -am "$(curl -s https://whatthecommit.com/index.txt)"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GH_TOKEN }}
